### ISSUE TITLE
How to make miui led flash light  work？

### ISSUE THREAD

**Issue by imzf** [ryan-andri/android_kernel_santoni#4]
Hello I compiled a kernel，But I found the MIUI camera flash can't be used, using other cameras app, the flash work is normal. And button flashlight in notification bar can not enable. I found that your kernel can work properly. Can you tell me, how do you do it? (I'm sorry, I'm not good at English, the translation software used)

**Comment by ryan-andri** [comment]
you need commit:
33407a7a9baaa43e5ddd37f225e304f4f83e49de
and changes on camera stack file msm_flash.c by commit 367e0861906560559668cbf7667918497d397908

**Comment by imzf** [comment]
@ryan-andri Thank you very much. Thank you for taking the time to answer my questions. Now MIUI LED flash light works well。
I have a new problem, and when I use the kernel that I build and the kernel built by bitrvmpd, I have the same problem.Opening Hotspot will cause the mobile data connection to be unworking, can't connect to the Internet。Other people can connect to the Hotspot I created, but they can't access the Internet。Can you help me to fix the problem?
This is the log that I'm using bitrvmpd's Loup.Kernel-v3.18.93-N-20180203-wifi.
https://github.com/bitrvmpd/msm-3.18/files/1854408/Loup.Kernel-v3.18.93-N-20180203-wifi.log

**Comment by ryan-andri** [comment]
@imzf your welcome, happy to help ;)
nah its firmware problem, try rebase **ipa** driver from nougat source like this commit f3f3bc04b26c54271e335801d60d7113c2041a45, i prefer to latest caf nougat for it "**LA.UM.5.6.r1-06900-89xx.0**" it will fix that issue on MIUI, but that change not necessary for aosp, since aosp not really depended on firmware.
